console.log("ARAAY   2");
let arr=[1,2,3,4,5];
console.log("ARRAY1  :"+arr);
let arr2=[...arr,100,10000,1000];
console.log("ARAYY2  :"+arr2);
let arr3=arr.slice(0).concat(["a","b","c"]);
console.log("ARRAY3  :"+arr3);
let arr4=[].concat(arr);
console.log("ARRAY4   :"+arr4);
let arr5=[...arr,...arr2];
console.log(arr5);
console.log(arr5.length);
console.log(arr5[0]);
let str=['a','b','c'];
console.log(arr3[7].toUpperCase());
const a=[1,2,3];
a.push(100);
console.log(a);
a=[1,2,4];
console.log(a);